apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
    - name: lambda
      port: 4571
      targetPort: 4571
    - name: ui
      port: 8080
      targetPort: 8080
