apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: microservices-demo
 namespace: argocd
spec:
 project: default

 source:
   repoURL: https://github.com/axhukacisco/argotest.git
   targetRevision: HEAD
   path: apps

 destination:
   server: https://kubernetes.default.svc
   namespace: default

 syncPolicy:
   automated:
     prune: true
     selfHeal: true
