apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: python:3.10-slim
        command: ["sh", "-c"]
        args:
          - pip install flask requests && python /app/service-b.py
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: script-volume
          mountPath: /app/service-b.py
          subPath: service-b.py
      volumes:
      - name: script-volume
        configMap:
          name: service-b-script

